name: Build & Deploy Backend to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Heroku Container Registry
      uses: akhileshns/heroku-docker-login@v2
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push Docker image
      run: |
        cd automl-ai-backend
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web

    - name: Release on Heroku
      run: |
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME_BACKEND }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
