name: Build & Deploy Backend to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Enable Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to the Heroku Container Registry
      - name: Log in to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _                     # Heroku Container Registry username is always '_'
          password: ${{ secrets.HEROKU_API_KEY }}

      # 4. Build & push the Docker image
      - name: Build & push Docker image
        run: |
          cd automl-ai-backend
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web

      # 5. Release the pushed image via the Heroku API
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_BACKEND }}
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY" \
            -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "registry.heroku.com/'"$HEROKU_APP_NAME"'/web"
                }
              ]
            }'