name: Build & Deploy Backend to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _                     # literally an underscore
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Build & push Docker image
        run: |
          cd automl-ai-backend
          docker build --pull --progress=plain -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_BACKEND }}/web

      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_BACKEND }}
        run: |
          # PATCH formation to kick off the release
          curl -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation/web \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
              -H "Authorization: Bearer $HEROKU_API_KEY" \
              -d '{ "docker_image": "registry.heroku.com/'"$HEROKU_APP_NAME"'/web", "quantity": 1 }'

